// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahboipwbpyalpyzriizf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoYm9pcHdicHlhbHB5enJpaXpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYyNjQzOTQsImV4cCI6MjA4MTg0MDM5NH0.r3M4-1ezAtVz0IVuV5V_H8Jw30Sgv_z3Nala8CIeBB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});